version: "3.8"
services:
  server:
    build: ./
    image: seekplum/test-qr:test
    ports:
      - 8089:8089
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    sysctls:
      net.ipv4.tcp_tw_reuse: 1
